/**
 * Fields for entity. Use this when creating forms in React/Angular,
 * instead of giving string to each one, use it from here, so in case of
 * updating any fields you don't loose it.
 */

export const ResumeCompanyEntityFields = {
  visibility: "visibility",
  workspaceId: "workspaceId",
  linkerId: "linkerId",
  parentId: "parentId",
  uniqueId: "uniqueId",
  userId: "userId",
  placeCountryId: "placeCountryId",
  placeCountry: {
    visibility: "placeCountry.visibility",
    workspaceId: "placeCountry.workspaceId",
    linkerId: "placeCountry.linkerId",
    parentId: "placeCountry.parentId",
    uniqueId: "placeCountry.uniqueId",
    userId: "placeCountry.userId",
    translations: "placeCountry.translations",
    status: "placeCountry.status",
    flag: "placeCountry.flag",
    commonName: "placeCountry.commonName",
    officialName: "placeCountry.officialName",
    rank: "placeCountry.rank",
    updated: "placeCountry.updated",
    created: "placeCountry.created",
    createdFormatted: "placeCountry.createdFormatted",
    updatedFormatted: "placeCountry.updatedFormatted",
  },
  placeCountry$: "placeCountry",
  workCountryId: "workCountryId",
  workCountry: {
    visibility: "workCountry.visibility",
    workspaceId: "workCountry.workspaceId",
    linkerId: "workCountry.linkerId",
    parentId: "workCountry.parentId",
    uniqueId: "workCountry.uniqueId",
    userId: "workCountry.userId",
    translations: "workCountry.translations",
    status: "workCountry.status",
    flag: "workCountry.flag",
    commonName: "workCountry.commonName",
    officialName: "workCountry.officialName",
    rank: "workCountry.rank",
    updated: "workCountry.updated",
    created: "workCountry.created",
    createdFormatted: "workCountry.createdFormatted",
    updatedFormatted: "workCountry.updatedFormatted",
  },
  workCountry$: "workCountry",
  mainIndustryId: "mainIndustryId",
  mainIndustry: {
    visibility: "mainIndustry.visibility",
    workspaceId: "mainIndustry.workspaceId",
    linkerId: "mainIndustry.linkerId",
    parentId: "mainIndustry.parentId",
    uniqueId: "mainIndustry.uniqueId",
    userId: "mainIndustry.userId",
    translations: "mainIndustry.translations",
    name: "mainIndustry.name",
    rank: "mainIndustry.rank",
    updated: "mainIndustry.updated",
    created: "mainIndustry.created",
    createdFormatted: "mainIndustry.createdFormatted",
    updatedFormatted: "mainIndustry.updatedFormatted",
  },
  mainIndustry$: "mainIndustry",
  employeeCount: "employeeCount",
  rank: "rank",
  updated: "updated",
  created: "created",
  createdFormatted: "createdFormatted",
  updatedFormatted: "updatedFormatted",
};
