/**
 * Fields for entity. Use this when creating forms in React/Angular,
 * instead of giving string to each one, use it from here, so in case of
 * updating any fields you don't loose it.
 */

export const ResumeSkillEntityFields = {
  visibility: "visibility",
  workspaceId: "workspaceId",
  linkerId: "linkerId",
  parentId: "parentId",
  uniqueId: "uniqueId",
  userId: "userId",
  skillsetId: "skillsetId",
  skillset: {
    visibility: "skillset.visibility",
    workspaceId: "skillset.workspaceId",
    linkerId: "skillset.linkerId",
    parentId: "skillset.parentId",
    uniqueId: "skillset.uniqueId",
    userId: "skillset.userId",
    translations: "skillset.translations",
    name: "skillset.name",
    description: "skillset.description",
    attachmentsListId: "skillset.attachmentsListId",
    attachments: "skillset.attachments",
    categoryId: "skillset.categoryId",
    category: {
      visibility: "skillset.category.visibility",
      workspaceId: "skillset.category.workspaceId",
      linkerId: "skillset.category.linkerId",
      parentId: "skillset.category.parentId",
      uniqueId: "skillset.category.uniqueId",
      userId: "skillset.category.userId",
      translations: "skillset.category.translations",
      name: "skillset.category.name",
      rank: "skillset.category.rank",
      updated: "skillset.category.updated",
      created: "skillset.category.created",
      createdFormatted: "skillset.category.createdFormatted",
      updatedFormatted: "skillset.category.updatedFormatted",
    },
    category$: "category",
    rank: "skillset.rank",
    updated: "skillset.updated",
    created: "skillset.created",
    createdFormatted: "skillset.createdFormatted",
    updatedFormatted: "skillset.updatedFormatted",
  },
  skillset$: "skillset",
  rank: "rank",
  updated: "updated",
  created: "created",
  createdFormatted: "createdFormatted",
  updatedFormatted: "updatedFormatted",
};
