/**
 * Fields for entity. Use this when creating forms in React/Angular,
 * instead of giving string to each one, use it from here, so in case of
 * updating any fields you don't loose it.
 */

export const AcBankBranchEntityFields = {
  visibility: "visibility",
  workspaceId: "workspaceId",
  linkerId: "linkerId",
  parentId: "parentId",
  parent: "parent",
  parent$: "parent",
  uniqueId: "uniqueId",
  userId: "userId",
  translations: "translations",
  locationId: "locationId",
  location: {
    visibility: "location.visibility",
    workspaceId: "location.workspaceId",
    linkerId: "location.linkerId",
    parentId: "location.parentId",
    parent: "location.parent",
    parent$: "parent",
    uniqueId: "location.uniqueId",
    userId: "location.userId",
    translations: "location.translations",
    name: "location.name",
    code: "location.code",
    typeId: "location.typeId",
    type: {
      visibility: "location.type.visibility",
      workspaceId: "location.type.workspaceId",
      linkerId: "location.type.linkerId",
      parentId: "location.type.parentId",
      parent: "location.type.parent",
      parent$: "parent",
      uniqueId: "location.type.uniqueId",
      userId: "location.type.userId",
      translations: "location.type.translations",
      name: "location.type.name",
      rank: "location.type.rank",
      updated: "location.type.updated",
      created: "location.type.created",
      createdFormatted: "location.type.createdFormatted",
      updatedFormatted: "location.type.updatedFormatted",
    },
    type$: "type",
    status: "location.status",
    flag: "location.flag",
    officialName: "location.officialName",
    rank: "location.rank",
    updated: "location.updated",
    created: "location.created",
    createdFormatted: "location.createdFormatted",
    updatedFormatted: "location.updatedFormatted",
    children: "location.children",
  },
  location$: "location",
  name: "name",
  bankId: "bankId",
  bank: {
    visibility: "bank.visibility",
    workspaceId: "bank.workspaceId",
    linkerId: "bank.linkerId",
    parentId: "bank.parentId",
    parent: "bank.parent",
    parent$: "parent",
    uniqueId: "bank.uniqueId",
    userId: "bank.userId",
    translations: "bank.translations",
    name: "bank.name",
    rank: "bank.rank",
    updated: "bank.updated",
    created: "bank.created",
    createdFormatted: "bank.createdFormatted",
    updatedFormatted: "bank.updatedFormatted",
  },
  bank$: "bank",
  rank: "rank",
  updated: "updated",
  created: "created",
  createdFormatted: "createdFormatted",
  updatedFormatted: "updatedFormatted",
};
