#ifndef gpio_state_csql_h
#define gpio_state_csql_h
#include "./GpioStateDefinitions.dyno.h"
const char * gpio_state_create_sql = "CREATE TABLE IF NOT EXISTS fb_gpio_state_entities ("
        "`visibility` TEXT,"
        "`parent_id` TEXT,"
        "`linker_id` TEXT,"
        "`workspace_id` TEXT,"
        "`linked_id` TEXT,"
        "`unique_id` TEXT,"
        "`user_id` TEXT,"
        "`rank` INTEGER,"
        "`updated` INTEGER,"
        "`created` INTEGER,"
        "`created_formatted` TEXT,"
        "`updated_formatted` TEXT,"
        "`gpio_mode_id` TEXT,"
        "`gpio_index_snapshot` INTEGER,"
        "`gpio_mode_snapshot` INTEGER,"
        "`gpio_value_snapshot` INTEGER,"
        "`gpio_id` TEXT,"
    "PRIMARY KEY (unique_id)"
" );";
const char * gpio_state_query_sql = "SELECT * FROM fb_gpio_state_entities "
        " LEFT JOIN fb_gpio_mode_entities on fb_gpio_state_entities.gpio_mode_id = fb_gpio_mode_entities.unique_id "
        " LEFT JOIN fb_gpio_entities on fb_gpio_state_entities.gpio_id = fb_gpio_entities.unique_id "
;
const char * gpio_state_insert_sql = "INSERT INTO fb_gpio_state_entities values ("
    "'%q',"
    "'%q',"
    "'%q',"
    "'%q',"
    "'%q',"
    "'%q',"
    "'%q',"
    "%f,"
    "%f,"
    "%f,"
    "'%q',"
    "'%q',"
    "'%q',"
    "%f,"
    "%f,"
    "%f,"
    "'%q'"
" );";
;
#endif