/**
 * Fields for entity. Use this when creating forms in React/Angular,
 * instead of giving string to each one, use it from here, so in case of
 * updating any fields you don't loose it.
 */

export const UserRoleWorkspaceEntityFields = {
  visibility: "visibility",
  workspaceId: "workspaceId",
  linkerId: "linkerId",
  parentId: "parentId",
  uniqueId: "uniqueId",
  userId: "userId",
  user: {
    visibility: "user.visibility",
    workspaceId: "user.workspaceId",
    linkerId: "user.linkerId",
    parentId: "user.parentId",
    uniqueId: "user.uniqueId",
    userId: "user.userId",
    firstName: "user.firstName",
    lastName: "user.lastName",
    photo: "user.photo",
    rank: "user.rank",
    updated: "user.updated",
    created: "user.created",
    createdFormatted: "user.createdFormatted",
    updatedFormatted: "user.updatedFormatted",
  },
  user$: "user",
  roleId: "roleId",
  role: {
    visibility: "role.visibility",
    workspaceId: "role.workspaceId",
    linkerId: "role.linkerId",
    parentId: "role.parentId",
    uniqueId: "role.uniqueId",
    userId: "role.userId",
    name: "role.name",
    capabilitiesListId: "role.capabilitiesListId",
    capabilities: {
      visibility: "role.capabilities.visibility",
      workspaceId: "role.capabilities.workspaceId",
      linkerId: "role.capabilities.linkerId",
      parentId: "role.capabilities.parentId",
      uniqueId: "role.capabilities.uniqueId",
      userId: "role.capabilities.userId",
      name: "role.capabilities.name",
      rank: "role.capabilities.rank",
      updated: "role.capabilities.updated",
      created: "role.capabilities.created",
      createdFormatted: "role.capabilities.createdFormatted",
      updatedFormatted: "role.capabilities.updatedFormatted",
    },
    capabilities$: "capabilities",
    rank: "role.rank",
    updated: "role.updated",
    created: "role.created",
    createdFormatted: "role.createdFormatted",
    updatedFormatted: "role.updatedFormatted",
  },
  role$: "role",
  workspace: {
    visibility: "workspace.visibility",
    workspaceId: "workspace.workspaceId",
    linkerId: "workspace.linkerId",
    parentId: "workspace.parentId",
    uniqueId: "workspace.uniqueId",
    userId: "workspace.userId",
    description: "workspace.description",
    name: "workspace.name",
    rank: "workspace.rank",
    updated: "workspace.updated",
    created: "workspace.created",
    createdFormatted: "workspace.createdFormatted",
    updatedFormatted: "workspace.updatedFormatted",
  },
  workspace$: "workspace",
  rank: "rank",
  updated: "updated",
  created: "created",
  createdFormatted: "createdFormatted",
  updatedFormatted: "updatedFormatted",
};
