#ifndef gpio_csql_h
#define gpio_csql_h
#include "./GpioDefinitions.dyno.h"
const char * gpio_create_sql = "CREATE TABLE IF NOT EXISTS fb_gpio_entities ("
        "`visibility` TEXT,"
        "`parent_id` TEXT,"
        "`linker_id` TEXT,"
        "`workspace_id` TEXT,"
        "`linked_id` TEXT,"
        "`unique_id` TEXT,"
        "`user_id` TEXT,"
        "`rank` INTEGER,"
        "`updated` INTEGER,"
        "`created` INTEGER,"
        "`created_formatted` TEXT,"
        "`updated_formatted` TEXT,"
        "`name` TEXT,"
        "`index` INTEGER,"
        "`analog_function` TEXT,"
        "`rtc_gpio` TEXT,"
        "`comments` TEXT,"
        "`mode_id` TEXT,"
    "PRIMARY KEY (unique_id)"
" );";
const char * gpio_query_sql = "SELECT * FROM fb_gpio_entities "
        " LEFT JOIN fb_gpio_mode_entities on fb_gpio_entities.mode_id = fb_gpio_mode_entities.unique_id "
;
const char * gpio_insert_sql = "INSERT INTO fb_gpio_entities values ("
    "'%q',"
    "'%q',"
    "'%q',"
    "'%q',"
    "'%q',"
    "'%q',"
    "'%q',"
    "%f,"
    "%f,"
    "%f,"
    "'%q',"
    "'%q',"
    "'%q',"
    "%f,"
    "'%q',"
    "'%q',"
    "'%q',"
    "'%q'"
" );";
;
#endif