/**
 * Fields for entity. Use this when creating forms in React/Angular,
 * instead of giving string to each one, use it from here, so in case of
 * updating any fields you don't loose it.
 */

export const AcBankBranchEntityFields = {
  visibility: "visibility",
  workspaceId: "workspaceId",
  linkerId: "linkerId",
  parentId: "parentId",
  uniqueId: "uniqueId",
  userId: "userId",
  translations: "translations",
  provinceId: "provinceId",
  province: {
    visibility: "province.visibility",
    workspaceId: "province.workspaceId",
    linkerId: "province.linkerId",
    parentId: "province.parentId",
    uniqueId: "province.uniqueId",
    userId: "province.userId",
    translations: "province.translations",
    name: "province.name",
    countryId: "province.countryId",
    country: {
      visibility: "province.country.visibility",
      workspaceId: "province.country.workspaceId",
      linkerId: "province.country.linkerId",
      parentId: "province.country.parentId",
      uniqueId: "province.country.uniqueId",
      userId: "province.country.userId",
      translations: "province.country.translations",
      status: "province.country.status",
      flag: "province.country.flag",
      commonName: "province.country.commonName",
      officialName: "province.country.officialName",
      rank: "province.country.rank",
      updated: "province.country.updated",
      created: "province.country.created",
      createdFormatted: "province.country.createdFormatted",
      updatedFormatted: "province.country.updatedFormatted",
    },
    country$: "country",
    rank: "province.rank",
    updated: "province.updated",
    created: "province.created",
    createdFormatted: "province.createdFormatted",
    updatedFormatted: "province.updatedFormatted",
  },
  province$: "province",
  cityId: "cityId",
  city: {
    visibility: "city.visibility",
    workspaceId: "city.workspaceId",
    linkerId: "city.linkerId",
    parentId: "city.parentId",
    uniqueId: "city.uniqueId",
    userId: "city.userId",
    name: "city.name",
    provinceId: "city.provinceId",
    province: {
      visibility: "city.province.visibility",
      workspaceId: "city.province.workspaceId",
      linkerId: "city.province.linkerId",
      parentId: "city.province.parentId",
      uniqueId: "city.province.uniqueId",
      userId: "city.province.userId",
      translations: "city.province.translations",
      name: "city.province.name",
      countryId: "city.province.countryId",
      country: {
        visibility: "city.province.country.visibility",
        workspaceId: "city.province.country.workspaceId",
        linkerId: "city.province.country.linkerId",
        parentId: "city.province.country.parentId",
        uniqueId: "city.province.country.uniqueId",
        userId: "city.province.country.userId",
        translations: "city.province.country.translations",
        status: "city.province.country.status",
        flag: "city.province.country.flag",
        commonName: "city.province.country.commonName",
        officialName: "city.province.country.officialName",
        rank: "city.province.country.rank",
        updated: "city.province.country.updated",
        created: "city.province.country.created",
        createdFormatted: "city.province.country.createdFormatted",
        updatedFormatted: "city.province.country.updatedFormatted",
      },
      country$: "country",
      rank: "city.province.rank",
      updated: "city.province.updated",
      created: "city.province.created",
      createdFormatted: "city.province.createdFormatted",
      updatedFormatted: "city.province.updatedFormatted",
    },
    province$: "province",
    stateId: "city.stateId",
    state: {
      visibility: "city.state.visibility",
      workspaceId: "city.state.workspaceId",
      linkerId: "city.state.linkerId",
      parentId: "city.state.parentId",
      uniqueId: "city.state.uniqueId",
      userId: "city.state.userId",
      translations: "city.state.translations",
      name: "city.state.name",
      rank: "city.state.rank",
      updated: "city.state.updated",
      created: "city.state.created",
      createdFormatted: "city.state.createdFormatted",
      updatedFormatted: "city.state.updatedFormatted",
    },
    state$: "state",
    countryId: "city.countryId",
    country: {
      visibility: "city.country.visibility",
      workspaceId: "city.country.workspaceId",
      linkerId: "city.country.linkerId",
      parentId: "city.country.parentId",
      uniqueId: "city.country.uniqueId",
      userId: "city.country.userId",
      translations: "city.country.translations",
      status: "city.country.status",
      flag: "city.country.flag",
      commonName: "city.country.commonName",
      officialName: "city.country.officialName",
      rank: "city.country.rank",
      updated: "city.country.updated",
      created: "city.country.created",
      createdFormatted: "city.country.createdFormatted",
      updatedFormatted: "city.country.updatedFormatted",
    },
    country$: "country",
    rank: "city.rank",
    updated: "city.updated",
    created: "city.created",
    createdFormatted: "city.createdFormatted",
    updatedFormatted: "city.updatedFormatted",
  },
  city$: "city",
  name: "name",
  bankId: "bankId",
  bank: {
    visibility: "bank.visibility",
    workspaceId: "bank.workspaceId",
    linkerId: "bank.linkerId",
    parentId: "bank.parentId",
    uniqueId: "bank.uniqueId",
    userId: "bank.userId",
    translations: "bank.translations",
    name: "bank.name",
    rank: "bank.rank",
    updated: "bank.updated",
    created: "bank.created",
    createdFormatted: "bank.createdFormatted",
    updatedFormatted: "bank.updatedFormatted",
  },
  bank$: "bank",
  rank: "rank",
  updated: "updated",
  created: "created",
  createdFormatted: "createdFormatted",
  updatedFormatted: "updatedFormatted",
};
