/**
 * Fields for entity. Use this when creating forms in React/Angular,
 * instead of giving string to each one, use it from here, so in case of
 * updating any fields you don't loose it.
 */

export const AcCheckStatusHistoryEntityFields = {
  visibility: "visibility",
  workspaceId: "workspaceId",
  linkerId: "linkerId",
  parentId: "parentId",
  uniqueId: "uniqueId",
  userId: "userId",
  translations: "translations",
  note: "note",
  fromStateId: "fromStateId",
  fromState: {
    visibility: "fromState.visibility",
    workspaceId: "fromState.workspaceId",
    linkerId: "fromState.linkerId",
    parentId: "fromState.parentId",
    uniqueId: "fromState.uniqueId",
    userId: "fromState.userId",
    translations: "fromState.translations",
    name: "fromState.name",
    rank: "fromState.rank",
    updated: "fromState.updated",
    created: "fromState.created",
    createdFormatted: "fromState.createdFormatted",
    updatedFormatted: "fromState.updatedFormatted",
  },
  fromState$: "fromState",
  checkId: "checkId",
  check: {
    visibility: "check.visibility",
    workspaceId: "check.workspaceId",
    linkerId: "check.linkerId",
    parentId: "check.parentId",
    uniqueId: "check.uniqueId",
    userId: "check.userId",
    customerId: "check.customerId",
    customer: {
      visibility: "check.customer.visibility",
      workspaceId: "check.customer.workspaceId",
      linkerId: "check.customer.linkerId",
      parentId: "check.customer.parentId",
      uniqueId: "check.customer.uniqueId",
      userId: "check.customer.userId",
      note: "check.customer.note",
      noteExcerpt: "check.customer.noteExcerpt",
      meetingNote: "check.customer.meetingNote",
      fullAddress: "check.customer.fullAddress",
      postalCode: "check.customer.postalCode",
      fullName: "check.customer.fullName",
      typeId: "check.customer.typeId",
      type: {
        visibility: "check.customer.type.visibility",
        workspaceId: "check.customer.type.workspaceId",
        linkerId: "check.customer.type.linkerId",
        parentId: "check.customer.type.parentId",
        uniqueId: "check.customer.type.uniqueId",
        userId: "check.customer.type.userId",
        translations: "check.customer.type.translations",
        title: "check.customer.type.title",
        rank: "check.customer.type.rank",
        updated: "check.customer.type.updated",
        created: "check.customer.type.created",
        createdFormatted: "check.customer.type.createdFormatted",
        updatedFormatted: "check.customer.type.updatedFormatted",
      },
      type$: "type",
      personalDataId: "check.customer.personalDataId",
      personalData: {
        visibility: "check.customer.personalData.visibility",
        workspaceId: "check.customer.personalData.workspaceId",
        linkerId: "check.customer.personalData.linkerId",
        parentId: "check.customer.personalData.parentId",
        uniqueId: "check.customer.personalData.uniqueId",
        userId: "check.customer.personalData.userId",
        translations: "check.customer.personalData.translations",
        firstName: "check.customer.personalData.firstName",
        lastName: "check.customer.personalData.lastName",
        phoneNumber: "check.customer.personalData.phoneNumber",
        nationalId: "check.customer.personalData.nationalId",
        rank: "check.customer.personalData.rank",
        updated: "check.customer.personalData.updated",
        created: "check.customer.personalData.created",
        createdFormatted: "check.customer.personalData.createdFormatted",
        updatedFormatted: "check.customer.personalData.updatedFormatted",
      },
      personalData$: "personalData",
      businessDataId: "check.customer.businessDataId",
      businessData: {
        visibility: "check.customer.businessData.visibility",
        workspaceId: "check.customer.businessData.workspaceId",
        linkerId: "check.customer.businessData.linkerId",
        parentId: "check.customer.businessData.parentId",
        uniqueId: "check.customer.businessData.uniqueId",
        userId: "check.customer.businessData.userId",
        translations: "check.customer.businessData.translations",
        name: "check.customer.businessData.name",
        taxNumber: "check.customer.businessData.taxNumber",
        contactPeople: "check.customer.businessData.contactPeople",
        rank: "check.customer.businessData.rank",
        updated: "check.customer.businessData.updated",
        created: "check.customer.businessData.created",
        createdFormatted: "check.customer.businessData.createdFormatted",
        updatedFormatted: "check.customer.businessData.updatedFormatted",
      },
      businessData$: "businessData",
      locationsListId: "check.customer.locationsListId",
      locations: {
        visibility: "check.customer.locations.visibility",
        workspaceId: "check.customer.locations.workspaceId",
        linkerId: "check.customer.locations.linkerId",
        parentId: "check.customer.locations.parentId",
        uniqueId: "check.customer.locations.uniqueId",
        userId: "check.customer.locations.userId",
        lat: "check.customer.locations.lat",
        lng: "check.customer.locations.lng",
        physicalAddress: "check.customer.locations.physicalAddress",
        rank: "check.customer.locations.rank",
        updated: "check.customer.locations.updated",
        created: "check.customer.locations.created",
        createdFormatted: "check.customer.locations.createdFormatted",
        updatedFormatted: "check.customer.locations.updatedFormatted",
      },
      locations$: "locations",
      rank: "check.customer.rank",
      updated: "check.customer.updated",
      created: "check.customer.created",
      createdFormatted: "check.customer.createdFormatted",
      updatedFormatted: "check.customer.updatedFormatted",
    },
    customer$: "customer",
    dueDate: "check.dueDate",
    dueDateFormatted: "check.dueDateFormatted",
    issueDate: "check.issueDate",
    issueDateFormatted: "check.issueDateFormatted",
    bankBranchId: "check.bankBranchId",
    bankBranch: {
      visibility: "check.bankBranch.visibility",
      workspaceId: "check.bankBranch.workspaceId",
      linkerId: "check.bankBranch.linkerId",
      parentId: "check.bankBranch.parentId",
      uniqueId: "check.bankBranch.uniqueId",
      userId: "check.bankBranch.userId",
      translations: "check.bankBranch.translations",
      provinceId: "check.bankBranch.provinceId",
      province: {
        visibility: "check.bankBranch.province.visibility",
        workspaceId: "check.bankBranch.province.workspaceId",
        linkerId: "check.bankBranch.province.linkerId",
        parentId: "check.bankBranch.province.parentId",
        uniqueId: "check.bankBranch.province.uniqueId",
        userId: "check.bankBranch.province.userId",
        translations: "check.bankBranch.province.translations",
        name: "check.bankBranch.province.name",
        countryId: "check.bankBranch.province.countryId",
        country: {
          visibility: "check.bankBranch.province.country.visibility",
          workspaceId: "check.bankBranch.province.country.workspaceId",
          linkerId: "check.bankBranch.province.country.linkerId",
          parentId: "check.bankBranch.province.country.parentId",
          uniqueId: "check.bankBranch.province.country.uniqueId",
          userId: "check.bankBranch.province.country.userId",
          translations: "check.bankBranch.province.country.translations",
          status: "check.bankBranch.province.country.status",
          flag: "check.bankBranch.province.country.flag",
          commonName: "check.bankBranch.province.country.commonName",
          officialName: "check.bankBranch.province.country.officialName",
          rank: "check.bankBranch.province.country.rank",
          updated: "check.bankBranch.province.country.updated",
          created: "check.bankBranch.province.country.created",
          createdFormatted:
            "check.bankBranch.province.country.createdFormatted",
          updatedFormatted:
            "check.bankBranch.province.country.updatedFormatted",
        },
        country$: "country",
        rank: "check.bankBranch.province.rank",
        updated: "check.bankBranch.province.updated",
        created: "check.bankBranch.province.created",
        createdFormatted: "check.bankBranch.province.createdFormatted",
        updatedFormatted: "check.bankBranch.province.updatedFormatted",
      },
      province$: "province",
      cityId: "check.bankBranch.cityId",
      city: {
        visibility: "check.bankBranch.city.visibility",
        workspaceId: "check.bankBranch.city.workspaceId",
        linkerId: "check.bankBranch.city.linkerId",
        parentId: "check.bankBranch.city.parentId",
        uniqueId: "check.bankBranch.city.uniqueId",
        userId: "check.bankBranch.city.userId",
        name: "check.bankBranch.city.name",
        provinceId: "check.bankBranch.city.provinceId",
        province: {
          visibility: "check.bankBranch.city.province.visibility",
          workspaceId: "check.bankBranch.city.province.workspaceId",
          linkerId: "check.bankBranch.city.province.linkerId",
          parentId: "check.bankBranch.city.province.parentId",
          uniqueId: "check.bankBranch.city.province.uniqueId",
          userId: "check.bankBranch.city.province.userId",
          translations: "check.bankBranch.city.province.translations",
          name: "check.bankBranch.city.province.name",
          countryId: "check.bankBranch.city.province.countryId",
          country: {
            visibility: "check.bankBranch.city.province.country.visibility",
            workspaceId: "check.bankBranch.city.province.country.workspaceId",
            linkerId: "check.bankBranch.city.province.country.linkerId",
            parentId: "check.bankBranch.city.province.country.parentId",
            uniqueId: "check.bankBranch.city.province.country.uniqueId",
            userId: "check.bankBranch.city.province.country.userId",
            translations: "check.bankBranch.city.province.country.translations",
            status: "check.bankBranch.city.province.country.status",
            flag: "check.bankBranch.city.province.country.flag",
            commonName: "check.bankBranch.city.province.country.commonName",
            officialName: "check.bankBranch.city.province.country.officialName",
            rank: "check.bankBranch.city.province.country.rank",
            updated: "check.bankBranch.city.province.country.updated",
            created: "check.bankBranch.city.province.country.created",
            createdFormatted:
              "check.bankBranch.city.province.country.createdFormatted",
            updatedFormatted:
              "check.bankBranch.city.province.country.updatedFormatted",
          },
          country$: "country",
          rank: "check.bankBranch.city.province.rank",
          updated: "check.bankBranch.city.province.updated",
          created: "check.bankBranch.city.province.created",
          createdFormatted: "check.bankBranch.city.province.createdFormatted",
          updatedFormatted: "check.bankBranch.city.province.updatedFormatted",
        },
        province$: "province",
        stateId: "check.bankBranch.city.stateId",
        state: {
          visibility: "check.bankBranch.city.state.visibility",
          workspaceId: "check.bankBranch.city.state.workspaceId",
          linkerId: "check.bankBranch.city.state.linkerId",
          parentId: "check.bankBranch.city.state.parentId",
          uniqueId: "check.bankBranch.city.state.uniqueId",
          userId: "check.bankBranch.city.state.userId",
          translations: "check.bankBranch.city.state.translations",
          name: "check.bankBranch.city.state.name",
          rank: "check.bankBranch.city.state.rank",
          updated: "check.bankBranch.city.state.updated",
          created: "check.bankBranch.city.state.created",
          createdFormatted: "check.bankBranch.city.state.createdFormatted",
          updatedFormatted: "check.bankBranch.city.state.updatedFormatted",
        },
        state$: "state",
        countryId: "check.bankBranch.city.countryId",
        country: {
          visibility: "check.bankBranch.city.country.visibility",
          workspaceId: "check.bankBranch.city.country.workspaceId",
          linkerId: "check.bankBranch.city.country.linkerId",
          parentId: "check.bankBranch.city.country.parentId",
          uniqueId: "check.bankBranch.city.country.uniqueId",
          userId: "check.bankBranch.city.country.userId",
          translations: "check.bankBranch.city.country.translations",
          status: "check.bankBranch.city.country.status",
          flag: "check.bankBranch.city.country.flag",
          commonName: "check.bankBranch.city.country.commonName",
          officialName: "check.bankBranch.city.country.officialName",
          rank: "check.bankBranch.city.country.rank",
          updated: "check.bankBranch.city.country.updated",
          created: "check.bankBranch.city.country.created",
          createdFormatted: "check.bankBranch.city.country.createdFormatted",
          updatedFormatted: "check.bankBranch.city.country.updatedFormatted",
        },
        country$: "country",
        rank: "check.bankBranch.city.rank",
        updated: "check.bankBranch.city.updated",
        created: "check.bankBranch.city.created",
        createdFormatted: "check.bankBranch.city.createdFormatted",
        updatedFormatted: "check.bankBranch.city.updatedFormatted",
      },
      city$: "city",
      name: "check.bankBranch.name",
      bankId: "check.bankBranch.bankId",
      bank: {
        visibility: "check.bankBranch.bank.visibility",
        workspaceId: "check.bankBranch.bank.workspaceId",
        linkerId: "check.bankBranch.bank.linkerId",
        parentId: "check.bankBranch.bank.parentId",
        uniqueId: "check.bankBranch.bank.uniqueId",
        userId: "check.bankBranch.bank.userId",
        translations: "check.bankBranch.bank.translations",
        name: "check.bankBranch.bank.name",
        rank: "check.bankBranch.bank.rank",
        updated: "check.bankBranch.bank.updated",
        created: "check.bankBranch.bank.created",
        createdFormatted: "check.bankBranch.bank.createdFormatted",
        updatedFormatted: "check.bankBranch.bank.updatedFormatted",
      },
      bank$: "bank",
      rank: "check.bankBranch.rank",
      updated: "check.bankBranch.updated",
      created: "check.bankBranch.created",
      createdFormatted: "check.bankBranch.createdFormatted",
      updatedFormatted: "check.bankBranch.updatedFormatted",
    },
    bankBranch$: "bankBranch",
    recipientBankBranchId: "check.recipientBankBranchId",
    recipientBankBranch: {
      visibility: "check.recipientBankBranch.visibility",
      workspaceId: "check.recipientBankBranch.workspaceId",
      linkerId: "check.recipientBankBranch.linkerId",
      parentId: "check.recipientBankBranch.parentId",
      uniqueId: "check.recipientBankBranch.uniqueId",
      userId: "check.recipientBankBranch.userId",
      translations: "check.recipientBankBranch.translations",
      provinceId: "check.recipientBankBranch.provinceId",
      province: {
        visibility: "check.recipientBankBranch.province.visibility",
        workspaceId: "check.recipientBankBranch.province.workspaceId",
        linkerId: "check.recipientBankBranch.province.linkerId",
        parentId: "check.recipientBankBranch.province.parentId",
        uniqueId: "check.recipientBankBranch.province.uniqueId",
        userId: "check.recipientBankBranch.province.userId",
        translations: "check.recipientBankBranch.province.translations",
        name: "check.recipientBankBranch.province.name",
        countryId: "check.recipientBankBranch.province.countryId",
        country: {
          visibility: "check.recipientBankBranch.province.country.visibility",
          workspaceId: "check.recipientBankBranch.province.country.workspaceId",
          linkerId: "check.recipientBankBranch.province.country.linkerId",
          parentId: "check.recipientBankBranch.province.country.parentId",
          uniqueId: "check.recipientBankBranch.province.country.uniqueId",
          userId: "check.recipientBankBranch.province.country.userId",
          translations:
            "check.recipientBankBranch.province.country.translations",
          status: "check.recipientBankBranch.province.country.status",
          flag: "check.recipientBankBranch.province.country.flag",
          commonName: "check.recipientBankBranch.province.country.commonName",
          officialName:
            "check.recipientBankBranch.province.country.officialName",
          rank: "check.recipientBankBranch.province.country.rank",
          updated: "check.recipientBankBranch.province.country.updated",
          created: "check.recipientBankBranch.province.country.created",
          createdFormatted:
            "check.recipientBankBranch.province.country.createdFormatted",
          updatedFormatted:
            "check.recipientBankBranch.province.country.updatedFormatted",
        },
        country$: "country",
        rank: "check.recipientBankBranch.province.rank",
        updated: "check.recipientBankBranch.province.updated",
        created: "check.recipientBankBranch.province.created",
        createdFormatted: "check.recipientBankBranch.province.createdFormatted",
        updatedFormatted: "check.recipientBankBranch.province.updatedFormatted",
      },
      province$: "province",
      cityId: "check.recipientBankBranch.cityId",
      city: {
        visibility: "check.recipientBankBranch.city.visibility",
        workspaceId: "check.recipientBankBranch.city.workspaceId",
        linkerId: "check.recipientBankBranch.city.linkerId",
        parentId: "check.recipientBankBranch.city.parentId",
        uniqueId: "check.recipientBankBranch.city.uniqueId",
        userId: "check.recipientBankBranch.city.userId",
        name: "check.recipientBankBranch.city.name",
        provinceId: "check.recipientBankBranch.city.provinceId",
        province: {
          visibility: "check.recipientBankBranch.city.province.visibility",
          workspaceId: "check.recipientBankBranch.city.province.workspaceId",
          linkerId: "check.recipientBankBranch.city.province.linkerId",
          parentId: "check.recipientBankBranch.city.province.parentId",
          uniqueId: "check.recipientBankBranch.city.province.uniqueId",
          userId: "check.recipientBankBranch.city.province.userId",
          translations: "check.recipientBankBranch.city.province.translations",
          name: "check.recipientBankBranch.city.province.name",
          countryId: "check.recipientBankBranch.city.province.countryId",
          country: {
            visibility:
              "check.recipientBankBranch.city.province.country.visibility",
            workspaceId:
              "check.recipientBankBranch.city.province.country.workspaceId",
            linkerId:
              "check.recipientBankBranch.city.province.country.linkerId",
            parentId:
              "check.recipientBankBranch.city.province.country.parentId",
            uniqueId:
              "check.recipientBankBranch.city.province.country.uniqueId",
            userId: "check.recipientBankBranch.city.province.country.userId",
            translations:
              "check.recipientBankBranch.city.province.country.translations",
            status: "check.recipientBankBranch.city.province.country.status",
            flag: "check.recipientBankBranch.city.province.country.flag",
            commonName:
              "check.recipientBankBranch.city.province.country.commonName",
            officialName:
              "check.recipientBankBranch.city.province.country.officialName",
            rank: "check.recipientBankBranch.city.province.country.rank",
            updated: "check.recipientBankBranch.city.province.country.updated",
            created: "check.recipientBankBranch.city.province.country.created",
            createdFormatted:
              "check.recipientBankBranch.city.province.country.createdFormatted",
            updatedFormatted:
              "check.recipientBankBranch.city.province.country.updatedFormatted",
          },
          country$: "country",
          rank: "check.recipientBankBranch.city.province.rank",
          updated: "check.recipientBankBranch.city.province.updated",
          created: "check.recipientBankBranch.city.province.created",
          createdFormatted:
            "check.recipientBankBranch.city.province.createdFormatted",
          updatedFormatted:
            "check.recipientBankBranch.city.province.updatedFormatted",
        },
        province$: "province",
        stateId: "check.recipientBankBranch.city.stateId",
        state: {
          visibility: "check.recipientBankBranch.city.state.visibility",
          workspaceId: "check.recipientBankBranch.city.state.workspaceId",
          linkerId: "check.recipientBankBranch.city.state.linkerId",
          parentId: "check.recipientBankBranch.city.state.parentId",
          uniqueId: "check.recipientBankBranch.city.state.uniqueId",
          userId: "check.recipientBankBranch.city.state.userId",
          translations: "check.recipientBankBranch.city.state.translations",
          name: "check.recipientBankBranch.city.state.name",
          rank: "check.recipientBankBranch.city.state.rank",
          updated: "check.recipientBankBranch.city.state.updated",
          created: "check.recipientBankBranch.city.state.created",
          createdFormatted:
            "check.recipientBankBranch.city.state.createdFormatted",
          updatedFormatted:
            "check.recipientBankBranch.city.state.updatedFormatted",
        },
        state$: "state",
        countryId: "check.recipientBankBranch.city.countryId",
        country: {
          visibility: "check.recipientBankBranch.city.country.visibility",
          workspaceId: "check.recipientBankBranch.city.country.workspaceId",
          linkerId: "check.recipientBankBranch.city.country.linkerId",
          parentId: "check.recipientBankBranch.city.country.parentId",
          uniqueId: "check.recipientBankBranch.city.country.uniqueId",
          userId: "check.recipientBankBranch.city.country.userId",
          translations: "check.recipientBankBranch.city.country.translations",
          status: "check.recipientBankBranch.city.country.status",
          flag: "check.recipientBankBranch.city.country.flag",
          commonName: "check.recipientBankBranch.city.country.commonName",
          officialName: "check.recipientBankBranch.city.country.officialName",
          rank: "check.recipientBankBranch.city.country.rank",
          updated: "check.recipientBankBranch.city.country.updated",
          created: "check.recipientBankBranch.city.country.created",
          createdFormatted:
            "check.recipientBankBranch.city.country.createdFormatted",
          updatedFormatted:
            "check.recipientBankBranch.city.country.updatedFormatted",
        },
        country$: "country",
        rank: "check.recipientBankBranch.city.rank",
        updated: "check.recipientBankBranch.city.updated",
        created: "check.recipientBankBranch.city.created",
        createdFormatted: "check.recipientBankBranch.city.createdFormatted",
        updatedFormatted: "check.recipientBankBranch.city.updatedFormatted",
      },
      city$: "city",
      name: "check.recipientBankBranch.name",
      bankId: "check.recipientBankBranch.bankId",
      bank: {
        visibility: "check.recipientBankBranch.bank.visibility",
        workspaceId: "check.recipientBankBranch.bank.workspaceId",
        linkerId: "check.recipientBankBranch.bank.linkerId",
        parentId: "check.recipientBankBranch.bank.parentId",
        uniqueId: "check.recipientBankBranch.bank.uniqueId",
        userId: "check.recipientBankBranch.bank.userId",
        translations: "check.recipientBankBranch.bank.translations",
        name: "check.recipientBankBranch.bank.name",
        rank: "check.recipientBankBranch.bank.rank",
        updated: "check.recipientBankBranch.bank.updated",
        created: "check.recipientBankBranch.bank.created",
        createdFormatted: "check.recipientBankBranch.bank.createdFormatted",
        updatedFormatted: "check.recipientBankBranch.bank.updatedFormatted",
      },
      bank$: "bank",
      rank: "check.recipientBankBranch.rank",
      updated: "check.recipientBankBranch.updated",
      created: "check.recipientBankBranch.created",
      createdFormatted: "check.recipientBankBranch.createdFormatted",
      updatedFormatted: "check.recipientBankBranch.updatedFormatted",
    },
    recipientBankBranch$: "recipientBankBranch",
    recipientCustomerId: "check.recipientCustomerId",
    recipientCustomer: {
      visibility: "check.recipientCustomer.visibility",
      workspaceId: "check.recipientCustomer.workspaceId",
      linkerId: "check.recipientCustomer.linkerId",
      parentId: "check.recipientCustomer.parentId",
      uniqueId: "check.recipientCustomer.uniqueId",
      userId: "check.recipientCustomer.userId",
      note: "check.recipientCustomer.note",
      noteExcerpt: "check.recipientCustomer.noteExcerpt",
      meetingNote: "check.recipientCustomer.meetingNote",
      fullAddress: "check.recipientCustomer.fullAddress",
      postalCode: "check.recipientCustomer.postalCode",
      fullName: "check.recipientCustomer.fullName",
      typeId: "check.recipientCustomer.typeId",
      type: {
        visibility: "check.recipientCustomer.type.visibility",
        workspaceId: "check.recipientCustomer.type.workspaceId",
        linkerId: "check.recipientCustomer.type.linkerId",
        parentId: "check.recipientCustomer.type.parentId",
        uniqueId: "check.recipientCustomer.type.uniqueId",
        userId: "check.recipientCustomer.type.userId",
        translations: "check.recipientCustomer.type.translations",
        title: "check.recipientCustomer.type.title",
        rank: "check.recipientCustomer.type.rank",
        updated: "check.recipientCustomer.type.updated",
        created: "check.recipientCustomer.type.created",
        createdFormatted: "check.recipientCustomer.type.createdFormatted",
        updatedFormatted: "check.recipientCustomer.type.updatedFormatted",
      },
      type$: "type",
      personalDataId: "check.recipientCustomer.personalDataId",
      personalData: {
        visibility: "check.recipientCustomer.personalData.visibility",
        workspaceId: "check.recipientCustomer.personalData.workspaceId",
        linkerId: "check.recipientCustomer.personalData.linkerId",
        parentId: "check.recipientCustomer.personalData.parentId",
        uniqueId: "check.recipientCustomer.personalData.uniqueId",
        userId: "check.recipientCustomer.personalData.userId",
        translations: "check.recipientCustomer.personalData.translations",
        firstName: "check.recipientCustomer.personalData.firstName",
        lastName: "check.recipientCustomer.personalData.lastName",
        phoneNumber: "check.recipientCustomer.personalData.phoneNumber",
        nationalId: "check.recipientCustomer.personalData.nationalId",
        rank: "check.recipientCustomer.personalData.rank",
        updated: "check.recipientCustomer.personalData.updated",
        created: "check.recipientCustomer.personalData.created",
        createdFormatted:
          "check.recipientCustomer.personalData.createdFormatted",
        updatedFormatted:
          "check.recipientCustomer.personalData.updatedFormatted",
      },
      personalData$: "personalData",
      businessDataId: "check.recipientCustomer.businessDataId",
      businessData: {
        visibility: "check.recipientCustomer.businessData.visibility",
        workspaceId: "check.recipientCustomer.businessData.workspaceId",
        linkerId: "check.recipientCustomer.businessData.linkerId",
        parentId: "check.recipientCustomer.businessData.parentId",
        uniqueId: "check.recipientCustomer.businessData.uniqueId",
        userId: "check.recipientCustomer.businessData.userId",
        translations: "check.recipientCustomer.businessData.translations",
        name: "check.recipientCustomer.businessData.name",
        taxNumber: "check.recipientCustomer.businessData.taxNumber",
        contactPeople: "check.recipientCustomer.businessData.contactPeople",
        rank: "check.recipientCustomer.businessData.rank",
        updated: "check.recipientCustomer.businessData.updated",
        created: "check.recipientCustomer.businessData.created",
        createdFormatted:
          "check.recipientCustomer.businessData.createdFormatted",
        updatedFormatted:
          "check.recipientCustomer.businessData.updatedFormatted",
      },
      businessData$: "businessData",
      locationsListId: "check.recipientCustomer.locationsListId",
      locations: {
        visibility: "check.recipientCustomer.locations.visibility",
        workspaceId: "check.recipientCustomer.locations.workspaceId",
        linkerId: "check.recipientCustomer.locations.linkerId",
        parentId: "check.recipientCustomer.locations.parentId",
        uniqueId: "check.recipientCustomer.locations.uniqueId",
        userId: "check.recipientCustomer.locations.userId",
        lat: "check.recipientCustomer.locations.lat",
        lng: "check.recipientCustomer.locations.lng",
        physicalAddress: "check.recipientCustomer.locations.physicalAddress",
        rank: "check.recipientCustomer.locations.rank",
        updated: "check.recipientCustomer.locations.updated",
        created: "check.recipientCustomer.locations.created",
        createdFormatted: "check.recipientCustomer.locations.createdFormatted",
        updatedFormatted: "check.recipientCustomer.locations.updatedFormatted",
      },
      locations$: "locations",
      rank: "check.recipientCustomer.rank",
      updated: "check.recipientCustomer.updated",
      created: "check.recipientCustomer.created",
      createdFormatted: "check.recipientCustomer.createdFormatted",
      updatedFormatted: "check.recipientCustomer.updatedFormatted",
    },
    recipientCustomer$: "recipientCustomer",
    amount: "check.amount",
    amountFormatted: "check.amountFormatted",
    identifier: "check.identifier",
    currencyId: "check.currencyId",
    currency: {
      visibility: "check.currency.visibility",
      workspaceId: "check.currency.workspaceId",
      linkerId: "check.currency.linkerId",
      parentId: "check.currency.parentId",
      uniqueId: "check.currency.uniqueId",
      userId: "check.currency.userId",
      translations: "check.currency.translations",
      symbol: "check.currency.symbol",
      name: "check.currency.name",
      symbolNative: "check.currency.symbolNative",
      decimalDigits: "check.currency.decimalDigits",
      rounding: "check.currency.rounding",
      code: "check.currency.code",
      namePlural: "check.currency.namePlural",
      rank: "check.currency.rank",
      updated: "check.currency.updated",
      created: "check.currency.created",
      createdFormatted: "check.currency.createdFormatted",
      updatedFormatted: "check.currency.updatedFormatted",
    },
    currency$: "currency",
    statusId: "check.statusId",
    status: {
      visibility: "check.status.visibility",
      workspaceId: "check.status.workspaceId",
      linkerId: "check.status.linkerId",
      parentId: "check.status.parentId",
      uniqueId: "check.status.uniqueId",
      userId: "check.status.userId",
      translations: "check.status.translations",
      name: "check.status.name",
      rank: "check.status.rank",
      updated: "check.status.updated",
      created: "check.status.created",
      createdFormatted: "check.status.createdFormatted",
      updatedFormatted: "check.status.updatedFormatted",
    },
    status$: "status",
    rank: "check.rank",
    updated: "check.updated",
    created: "check.created",
    createdFormatted: "check.createdFormatted",
    updatedFormatted: "check.updatedFormatted",
  },
  check$: "check",
  toStateId: "toStateId",
  toState: {
    visibility: "toState.visibility",
    workspaceId: "toState.workspaceId",
    linkerId: "toState.linkerId",
    parentId: "toState.parentId",
    uniqueId: "toState.uniqueId",
    userId: "toState.userId",
    translations: "toState.translations",
    name: "toState.name",
    rank: "toState.rank",
    updated: "toState.updated",
    created: "toState.created",
    createdFormatted: "toState.createdFormatted",
    updatedFormatted: "toState.updatedFormatted",
  },
  toState$: "toState",
  rank: "rank",
  updated: "updated",
  created: "created",
  createdFormatted: "createdFormatted",
  updatedFormatted: "updatedFormatted",
};
