package iot

var PERM_ROOT_MQTTCLIENTCONNECTION_DELETE = "root/mqttclientconnection/delete"
var PERM_ROOT_MQTTCLIENTCONNECTION_POST = "root/mqttclientconnection/post"
var PERM_ROOT_MQTTCLIENTCONNECTION_PATCH = "root/mqttclientconnection/patch"
var PERM_ROOT_MQTTCLIENTCONNECTION_QUERY = "root/mqttclientconnection/query"
var PERM_ROOT_MQTTCLIENTCONNECTION = "root/mqttclientconnection"

var ALL_MQTTCLIENTCONNECTION_PERMISSIONS = []string{
	PERM_ROOT_MQTTCLIENTCONNECTION_DELETE,
	PERM_ROOT_MQTTCLIENTCONNECTION_POST,
	PERM_ROOT_MQTTCLIENTCONNECTION_PATCH,
	PERM_ROOT_MQTTCLIENTCONNECTION_QUERY,
	PERM_ROOT_MQTTCLIENTCONNECTION,
}
