/**
 * Fields for entity. Use this when creating forms in React/Angular,
 * instead of giving string to each one, use it from here, so in case of
 * updating any fields you don't loose it.
 */

export const GpioStateEntityFields = {
  visibility: "visibility",
  workspaceId: "workspaceId",
  linkerId: "linkerId",
  parentId: "parentId",
  uniqueId: "uniqueId",
  userId: "userId",
  gpioModeId: "gpioModeId",
  gpioMode: {
    visibility: "gpioMode.visibility",
    workspaceId: "gpioMode.workspaceId",
    linkerId: "gpioMode.linkerId",
    parentId: "gpioMode.parentId",
    uniqueId: "gpioMode.uniqueId",
    userId: "gpioMode.userId",
    translations: "gpioMode.translations",
    key: "gpioMode.key",
    index: "gpioMode.index",
    description: "gpioMode.description",
    rank: "gpioMode.rank",
    updated: "gpioMode.updated",
    created: "gpioMode.created",
    createdFormatted: "gpioMode.createdFormatted",
    updatedFormatted: "gpioMode.updatedFormatted",
  },
  gpioMode$: "gpioMode",
  gpioIndexSnapshot: "gpioIndexSnapshot",
  gpioModeSnapshot: "gpioModeSnapshot",
  gpioValueSnapshot: "gpioValueSnapshot",
  gpioId: "gpioId",
  gpio: {
    visibility: "gpio.visibility",
    workspaceId: "gpio.workspaceId",
    linkerId: "gpio.linkerId",
    parentId: "gpio.parentId",
    uniqueId: "gpio.uniqueId",
    userId: "gpio.userId",
    name: "gpio.name",
    index: "gpio.index",
    analogFunction: "gpio.analogFunction",
    rtcGpio: "gpio.rtcGpio",
    comments: "gpio.comments",
    modeId: "gpio.modeId",
    mode: {
      visibility: "gpio.mode.visibility",
      workspaceId: "gpio.mode.workspaceId",
      linkerId: "gpio.mode.linkerId",
      parentId: "gpio.mode.parentId",
      uniqueId: "gpio.mode.uniqueId",
      userId: "gpio.mode.userId",
      translations: "gpio.mode.translations",
      key: "gpio.mode.key",
      index: "gpio.mode.index",
      description: "gpio.mode.description",
      rank: "gpio.mode.rank",
      updated: "gpio.mode.updated",
      created: "gpio.mode.created",
      createdFormatted: "gpio.mode.createdFormatted",
      updatedFormatted: "gpio.mode.updatedFormatted",
    },
    mode$: "mode",
    rank: "gpio.rank",
    updated: "gpio.updated",
    created: "gpio.created",
    createdFormatted: "gpio.createdFormatted",
    updatedFormatted: "gpio.updatedFormatted",
  },
  gpio$: "gpio",
  rank: "rank",
  updated: "updated",
  created: "created",
  createdFormatted: "createdFormatted",
  updatedFormatted: "updatedFormatted",
};
