/**
 * Fields for entity. Use this when creating forms in React/Angular,
 * instead of giving string to each one, use it from here, so in case of
 * updating any fields you don't loose it.
 */

export const MqttConfigEntityFields = {
  visibility: "visibility",
  workspaceId: "workspaceId",
  linkerId: "linkerId",
  parentId: "parentId",
  uniqueId: "uniqueId",
  userId: "userId",
  ssl: "ssl",
  autoReconnect: "autoReconnect",
  cleanSession: "cleanSession",
  lastWillRetain: "lastWillRetain",
  port: "port",
  keepAlive: "keepAlive",
  connectTimeout: "connectTimeout",
  lastWillQos: "lastWillQos",
  clientId: "clientId",
  name: "name",
  host: "host",
  username: "username",
  password: "password",
  mqttVersionId: "mqttVersionId",
  mqttVersion: {
    visibility: "mqttVersion.visibility",
    workspaceId: "mqttVersion.workspaceId",
    linkerId: "mqttVersion.linkerId",
    parentId: "mqttVersion.parentId",
    uniqueId: "mqttVersion.uniqueId",
    userId: "mqttVersion.userId",
    version: "mqttVersion.version",
    rank: "mqttVersion.rank",
    updated: "mqttVersion.updated",
    created: "mqttVersion.created",
    createdFormatted: "mqttVersion.createdFormatted",
    updatedFormatted: "mqttVersion.updatedFormatted",
  },
  mqttVersion$: "mqttVersion",
  lastWillTopic: "lastWillTopic",
  lastWillPayload: "lastWillPayload",
  rank: "rank",
  updated: "updated",
  created: "created",
  createdFormatted: "createdFormatted",
  updatedFormatted: "updatedFormatted",
};
